sudo: false
language: elixir
elixir:
  - 1.0.5
  - 1.1.0
otp_release:
  - 17.3
  - 18.0
env:
  - MIX_ENV=test
script:
  - mix test --exclude expensive --cover
  - mix test --only expensive --cover
notifications:
  email:
    - paulschoenfelder@gmail.com
