sudo: false
language: elixir
elixir:
  - 1.0.0
otp_release:
  - 17.0
  - 17.1
env:
  - MIX_ENV=test
script:
  - mix test --exclude expensive --cover
  - mix test --only expensive --cover
notifications:
  email:
    - paulschoenfelder@gmail.com
