language: erlang
otp_release:
  - 17.0
#env:
  #- ELIXIR_VERSION=0.14.2
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir
  - make
  - cd ..
  #- wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  #- unzip -d elixir Precompiled.zip
before_script:
  #- export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
script:
  - MIX_ENV=all mix test
notifications:
  email:
    - paulschoenfelder@gmail.com
