sudo: false
language: elixir
elixir:
  - 1.0.0
otp_release:
  - 17.0
  - 17.1
env:
  - MIX_ENV=all
script:
  - MIX_ENV=all mix test --exclude expensive
  - MIX_ENV=all mix test --only expensive
notifications:
  email:
    - paulschoenfelder@gmail.com
